server:
  servlet:
    context-path: /
  port: 8082
spring:
  application:
    name: sc-bill
  zipkin:
    base-url: http://${ZIP_KIN_SERVER_HOST:localhost}:${ZIP_KIN_SERVER_PORT:9411}
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true
