server:
  servlet:
    context-path: /
  port: 8082
spring:
  application:
    name: sc-bill
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true
